# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  run-tests:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/node:lts
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - run: "apt-get update"
      - run: "apt-get install -y chromium"
      - checkout
      - run: "npm install"
      - run: "node ./node_modules/puppeteer/install.js"
      - run: "npm install -g backstopjs"
      - run:
          name: "Run cucumber tests"
          command: "npm test"
      - run:
          name: "Run backstopjs tests"
          command: "backstop test"


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  run-tests-workflow:
    jobs:
      - run-tests
